version: '3.8'

services:
  web:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - ./public:/app/public
    command: npm run start

volumes:
  nextjs_data:
